"""Canonical service key -> `diagrams` node class.

The `diagrams` package reorganises modules between releases (and a few icons
only exist in newer versions), so every entry is a *list of candidates* tried in
order. The first importable candidate wins; if none resolve we fall back to a
kind-appropriate generic icon rather than failing the render.

That design means a missing icon degrades one node, never the whole diagram.
"""

from __future__ import annotations

import functools
import importlib
from pathlib import Path
from typing import Any

from ..models import ComponentKind as K

# Tiles we ship ourselves, for services `diagrams` has no icon for. Generated by
# `tools/generate_icons.py`; see that file for why they are role glyphs in brand
# colours rather than reproductions of vendor logos.
ASSETS_DIR = Path(__file__).resolve().parent / "assets"

CUSTOM_ICONS: dict[str, str] = {
    "saas.stripe": "stripe",
    "saas.sendgrid": "sendgrid",
    "saas.anthropic": "anthropic",
    "saas.openai": "openai",
    "saas.algolia": "algolia",
    "generic.vectordb": "vectordb",
    "generic.llmframework": "llmframework",
    "generic.ml": "ml",
    "generic.jwt": "jwt",
    "generic.dataframe": "dataframe",
}

# Each value is [(module_path, class_name), ...] in preference order.
Candidates = list[tuple[str, str]]

ICON_REGISTRY: dict[str, Candidates] = {
    # ===================== AWS =====================
    "aws.ec2": [("diagrams.aws.compute", "EC2")],
    "aws.ecs": [("diagrams.aws.compute", "ECS"), ("diagrams.aws.compute", "ElasticContainerService")],
    "aws.eks": [("diagrams.aws.compute", "EKS"), ("diagrams.aws.compute", "ElasticKubernetesService")],
    "aws.fargate": [("diagrams.aws.compute", "Fargate")],
    "aws.lambda": [("diagrams.aws.compute", "Lambda")],
    "aws.batch": [("diagrams.aws.compute", "Batch")],
    "aws.beanstalk": [("diagrams.aws.compute", "ElasticBeanstalk")],
    "aws.apprunner": [("diagrams.aws.compute", "AppRunner"), ("diagrams.aws.compute", "ECS")],
    "aws.ecr": [("diagrams.aws.compute", "ElasticContainerRegistry"), ("diagrams.aws.compute", "ECR")],
    "aws.s3": [("diagrams.aws.storage", "S3"), ("diagrams.aws.storage", "SimpleStorageServiceS3")],
    "aws.efs": [("diagrams.aws.storage", "EFS"), ("diagrams.aws.storage", "ElasticFileSystemEFS")],
    "aws.ebs": [("diagrams.aws.storage", "EBS")],
    "aws.backup": [("diagrams.aws.storage", "Backup")],
    "aws.rds": [("diagrams.aws.database", "RDS")],
    "aws.aurora": [("diagrams.aws.database", "Aurora"), ("diagrams.aws.database", "RDS")],
    "aws.dynamodb": [("diagrams.aws.database", "Dynamodb"), ("diagrams.aws.database", "DynamodbTable")],
    "aws.elasticache": [("diagrams.aws.database", "ElastiCache"), ("diagrams.aws.database", "Elasticache")],
    "aws.redshift": [("diagrams.aws.analytics", "Redshift"), ("diagrams.aws.database", "Redshift")],
    "aws.documentdb": [("diagrams.aws.database", "DocumentdbMongodbCompatibility"),
                       ("diagrams.aws.database", "Documentdb")],
    "aws.neptune": [("diagrams.aws.database", "Neptune")],
    "aws.timestream": [("diagrams.aws.database", "Timestream")],
    "aws.sqs": [("diagrams.aws.integration", "SQS"), ("diagrams.aws.integration", "SimpleQueueServiceSqs")],
    "aws.sns": [("diagrams.aws.integration", "SNS"), ("diagrams.aws.integration", "SimpleNotificationServiceSns")],
    "aws.eventbridge": [("diagrams.aws.integration", "Eventbridge")],
    "aws.stepfunctions": [("diagrams.aws.integration", "StepFunctions"), ("diagrams.aws.integration", "SF")],
    "aws.appsync": [("diagrams.aws.mobile", "Appsync"), ("diagrams.aws.integration", "Appsync")],
    "aws.mq": [("diagrams.aws.integration", "MQ")],
    "aws.kinesis": [("diagrams.aws.analytics", "Kinesis")],
    "aws.firehose": [("diagrams.aws.analytics", "KinesisDataFirehose"), ("diagrams.aws.analytics", "Kinesis")],
    "aws.msk": [("diagrams.aws.analytics", "ManagedStreamingForKafka"), ("diagrams.aws.analytics", "Kinesis")],
    "aws.glue": [("diagrams.aws.analytics", "Glue")],
    "aws.athena": [("diagrams.aws.analytics", "Athena")],
    "aws.emr": [("diagrams.aws.analytics", "EMR")],
    "aws.quicksight": [("diagrams.aws.analytics", "Quicksight")],
    "aws.opensearch": [("diagrams.aws.analytics", "ElasticsearchService"),
                       ("diagrams.aws.analytics", "Opensearch")],
    "aws.apigateway": [("diagrams.aws.network", "APIGateway"), ("diagrams.aws.mobile", "APIGateway")],
    "aws.elb": [("diagrams.aws.network", "ELB"), ("diagrams.aws.network", "ElasticLoadBalancing")],
    "aws.alb": [("diagrams.aws.network", "ALB"), ("diagrams.aws.network", "ElbApplicationLoadBalancer"),
                ("diagrams.aws.network", "ELB")],
    "aws.nlb": [("diagrams.aws.network", "NLB"), ("diagrams.aws.network", "ElbNetworkLoadBalancer"),
                ("diagrams.aws.network", "ELB")],
    "aws.cloudfront": [("diagrams.aws.network", "CloudFront")],
    "aws.route53": [("diagrams.aws.network", "Route53")],
    "aws.vpc": [("diagrams.aws.network", "VPC")],
    "aws.subnet": [("diagrams.aws.network", "PrivateSubnet"), ("diagrams.aws.network", "VPC")],
    "aws.natgateway": [("diagrams.aws.network", "NATGateway")],
    "aws.cognito": [("diagrams.aws.security", "Cognito")],
    "aws.iam": [("diagrams.aws.security", "IAM"), ("diagrams.aws.security", "IdentityAndAccessManagementIam")],
    "aws.kms": [("diagrams.aws.security", "KMS"), ("diagrams.aws.security", "KeyManagementService")],
    "aws.secretsmanager": [("diagrams.aws.security", "SecretsManager")],
    "aws.waf": [("diagrams.aws.security", "WAF"), ("diagrams.aws.security", "WebApplicationFirewall")],
    "aws.shield": [("diagrams.aws.security", "Shield")],
    "aws.cloudwatch": [("diagrams.aws.management", "Cloudwatch")],
    "aws.cloudformation": [("diagrams.aws.management", "Cloudformation")],
    "aws.cloudtrail": [("diagrams.aws.management", "Cloudtrail")],
    "aws.systemsmanager": [("diagrams.aws.management", "SystemsManager")],
    "aws.sagemaker": [("diagrams.aws.ml", "Sagemaker")],
    "aws.bedrock": [("diagrams.aws.ml", "Bedrock"), ("diagrams.aws.ml", "Sagemaker")],
    "aws.rekognition": [("diagrams.aws.ml", "Rekognition")],
    "aws.amplify": [("diagrams.aws.mobile", "Amplify")],
    "aws.codepipeline": [("diagrams.aws.devtools", "Codepipeline")],
    "aws.codebuild": [("diagrams.aws.devtools", "Codebuild")],
    "aws.sdk": [("diagrams.aws.general", "General"), ("diagrams.aws.compute", "EC2")],

    # ===================== Azure =====================
    "azure.vm": [("diagrams.azure.compute", "VM"), ("diagrams.azure.compute", "VirtualMachine")],
    "azure.vmss": [("diagrams.azure.compute", "VMScaleSet"), ("diagrams.azure.compute", "VM")],
    "azure.functions": [("diagrams.azure.compute", "FunctionApps"), ("diagrams.azure.compute", "FunctionApp")],
    "azure.appservice": [("diagrams.azure.web", "AppServices"), ("diagrams.azure.compute", "AppServices")],
    "azure.appserviceplan": [("diagrams.azure.web", "AppServicePlans"), ("diagrams.azure.web", "AppServices")],
    "azure.aks": [("diagrams.azure.compute", "KubernetesServices"), ("diagrams.azure.compute", "AKS")],
    "azure.containerapps": [("diagrams.azure.compute", "ContainerApps"),
                            ("diagrams.azure.compute", "ContainerInstances")],
    "azure.containerinstances": [("diagrams.azure.compute", "ContainerInstances")],
    "azure.acr": [("diagrams.azure.compute", "ContainerRegistries")],
    "azure.storageaccount": [("diagrams.azure.storage", "StorageAccounts")],
    "azure.blobstorage": [("diagrams.azure.storage", "BlobStorage"), ("diagrams.azure.storage", "StorageAccounts")],
    "azure.queuestorage": [("diagrams.azure.storage", "QueuesStorage"), ("diagrams.azure.storage", "StorageAccounts")],
    "azure.tablestorage": [("diagrams.azure.storage", "TableStorage"), ("diagrams.azure.storage", "StorageAccounts")],
    "azure.datalake": [("diagrams.azure.storage", "DataLakeStorage"), ("diagrams.azure.storage", "StorageAccounts")],
    "azure.sqldatabase": [("diagrams.azure.database", "SQLDatabases")],
    "azure.sqlserver": [("diagrams.azure.database", "SQLServers"), ("diagrams.azure.database", "SQLDatabases")],
    "azure.cosmosdb": [("diagrams.azure.database", "CosmosDb")],
    "azure.postgresql": [("diagrams.azure.database", "DatabaseForPostgresqlServers"),
                         ("diagrams.azure.database", "SQLDatabases")],
    "azure.mysql": [("diagrams.azure.database", "DatabaseForMysqlServers"),
                    ("diagrams.azure.database", "SQLDatabases")],
    "azure.redis": [("diagrams.azure.database", "CacheForRedis")],
    "azure.servicebus": [("diagrams.azure.integration", "ServiceBus")],
    "azure.eventgrid": [("diagrams.azure.integration", "EventGridTopics"),
                        ("diagrams.azure.integration", "EventGridDomains")],
    "azure.eventhubs": [("diagrams.azure.analytics", "EventHubs"),
                        ("diagrams.azure.analytics", "EventHubClusters")],
    "azure.logicapps": [("diagrams.azure.integration", "LogicApps")],
    "azure.apimanagement": [("diagrams.azure.integration", "APIManagement"),
                            ("diagrams.azure.web", "APIConnections")],
    "azure.appgateway": [("diagrams.azure.network", "ApplicationGateway")],
    "azure.loadbalancer": [("diagrams.azure.network", "LoadBalancers")],
    "azure.frontdoor": [("diagrams.azure.network", "FrontDoors"), ("diagrams.azure.network", "CDNProfiles")],
    "azure.cdn": [("diagrams.azure.network", "CDNProfiles")],
    "azure.vnet": [("diagrams.azure.network", "VirtualNetworks")],
    "azure.subnet": [("diagrams.azure.network", "Subnets"), ("diagrams.azure.network", "VirtualNetworks")],
    "azure.dns": [("diagrams.azure.network", "DNSZones")],
    "azure.keyvault": [("diagrams.azure.security", "KeyVaults")],
    "azure.activedirectory": [("diagrams.azure.identity", "ActiveDirectory"),
                              ("diagrams.azure.identity", "AppRegistrations")],
    "azure.appinsights": [("diagrams.azure.devops", "ApplicationInsights"),
                          ("diagrams.azure.management", "Monitor")],
    "azure.loganalytics": [("diagrams.azure.analytics", "LogAnalyticsWorkspaces"),
                           ("diagrams.azure.management", "Monitor")],
    "azure.monitor": [("diagrams.azure.management", "Monitor")],
    "azure.datafactory": [("diagrams.azure.analytics", "DataFactories")],
    "azure.synapse": [("diagrams.azure.analytics", "SynapseAnalytics"),
                      ("diagrams.azure.analytics", "DataLakeAnalytics")],
    "azure.databricks": [("diagrams.azure.analytics", "Databricks")],
    "azure.streamanalytics": [("diagrams.azure.analytics", "StreamAnalyticsJobs")],
    "azure.search": [("diagrams.azure.web", "Search"), ("diagrams.azure.analytics", "AnalysisServices")],
    "azure.cognitiveservices": [("diagrams.azure.ml", "CognitiveServices")],
    "azure.machinelearning": [("diagrams.azure.ml", "MachineLearningServiceWorkspaces"),
                              ("diagrams.azure.ml", "MachineLearningStudioWorkspaces")],
    "azure.devops": [("diagrams.azure.devops", "Pipelines"), ("diagrams.azure.devops", "Devops")],
    "azure.arm": [("diagrams.azure.general", "Resourcegroups"), ("diagrams.azure.general", "Managementgroups")],

    # ===================== GCP =====================
    "gcp.computeengine": [("diagrams.gcp.compute", "ComputeEngine"), ("diagrams.gcp.compute", "GCE")],
    "gcp.run": [("diagrams.gcp.compute", "Run")],
    "gcp.functions": [("diagrams.gcp.compute", "Functions"), ("diagrams.gcp.compute", "GCF")],
    "gcp.gke": [("diagrams.gcp.compute", "KubernetesEngine"), ("diagrams.gcp.compute", "GKE")],
    "gcp.appengine": [("diagrams.gcp.compute", "AppEngine"), ("diagrams.gcp.compute", "GAE")],
    "gcp.gcs": [("diagrams.gcp.storage", "GCS"), ("diagrams.gcp.storage", "Storage")],
    "gcp.filestore": [("diagrams.gcp.storage", "Filestore")],
    "gcp.sql": [("diagrams.gcp.database", "SQL"), ("diagrams.gcp.database", "Sql")],
    "gcp.firestore": [("diagrams.gcp.database", "Firestore")],
    "gcp.datastore": [("diagrams.gcp.database", "Datastore")],
    "gcp.bigtable": [("diagrams.gcp.database", "Bigtable"), ("diagrams.gcp.database", "BigTable")],
    "gcp.spanner": [("diagrams.gcp.database", "Spanner")],
    "gcp.memorystore": [("diagrams.gcp.database", "Memorystore")],
    "gcp.pubsub": [("diagrams.gcp.analytics", "PubSub"), ("diagrams.gcp.analytics", "Pubsub")],
    "gcp.tasks": [("diagrams.gcp.devtools", "Tasks"), ("diagrams.gcp.analytics", "PubSub")],
    "gcp.bigquery": [("diagrams.gcp.analytics", "BigQuery"), ("diagrams.gcp.analytics", "Bigquery")],
    "gcp.dataflow": [("diagrams.gcp.analytics", "Dataflow")],
    "gcp.dataproc": [("diagrams.gcp.analytics", "Dataproc")],
    "gcp.composer": [("diagrams.gcp.analytics", "Composer")],
    "gcp.loadbalancing": [("diagrams.gcp.network", "LoadBalancing")],
    "gcp.cdn": [("diagrams.gcp.network", "CDN")],
    "gcp.dns": [("diagrams.gcp.network", "DNS")],
    "gcp.vpc": [("diagrams.gcp.network", "VirtualPrivateCloud"), ("diagrams.gcp.network", "VPC")],
    "gcp.armor": [("diagrams.gcp.network", "Armor")],
    "gcp.apigateway": [("diagrams.gcp.api", "APIGateway"), ("diagrams.gcp.api", "Endpoints")],
    "gcp.endpoints": [("diagrams.gcp.api", "Endpoints")],
    "gcp.kms": [("diagrams.gcp.security", "KMS"), ("diagrams.gcp.security", "KeyManagementService")],
    "gcp.iam": [("diagrams.gcp.security", "Iam"), ("diagrams.gcp.security", "IAP")],
    "gcp.aiplatform": [("diagrams.gcp.ml", "AIPlatform"), ("diagrams.gcp.ml", "AutoML")],
    "gcp.build": [("diagrams.gcp.devtools", "Build")],
    "gcp.gcr": [("diagrams.gcp.devtools", "ContainerRegistry"), ("diagrams.gcp.devtools", "GCR")],

    # ===================== Kubernetes =====================
    "k8s.deployment": [("diagrams.k8s.compute", "Deployment"), ("diagrams.k8s.compute", "Deploy")],
    "k8s.pod": [("diagrams.k8s.compute", "Pod")],
    "k8s.statefulset": [("diagrams.k8s.compute", "StatefulSet"), ("diagrams.k8s.compute", "STS")],
    "k8s.daemonset": [("diagrams.k8s.compute", "DaemonSet"), ("diagrams.k8s.compute", "DS")],
    "k8s.replicaset": [("diagrams.k8s.compute", "ReplicaSet"), ("diagrams.k8s.compute", "RS")],
    "k8s.job": [("diagrams.k8s.compute", "Job")],
    "k8s.cronjob": [("diagrams.k8s.compute", "CronJob"), ("diagrams.k8s.compute", "Cronjob")],
    "k8s.service": [("diagrams.k8s.network", "Service"), ("diagrams.k8s.network", "SVC")],
    "k8s.ingress": [("diagrams.k8s.network", "Ingress"), ("diagrams.k8s.network", "Ing")],
    "k8s.pv": [("diagrams.k8s.storage", "PersistentVolume"), ("diagrams.k8s.storage", "PV")],
    "k8s.pvc": [("diagrams.k8s.storage", "PersistentVolumeClaim"), ("diagrams.k8s.storage", "PVC")],
    "k8s.configmap": [("diagrams.k8s.podconfig", "ConfigMap"), ("diagrams.k8s.podconfig", "CM")],
    "k8s.secret": [("diagrams.k8s.podconfig", "Secret")],
    "k8s.hpa": [("diagrams.k8s.clusterconfig", "HorizontalPodAutoscaler"),
                ("diagrams.k8s.clusterconfig", "HPA")],

    # ===================== On-prem / OSS =====================
    "onprem.postgresql": [("diagrams.onprem.database", "PostgreSQL"), ("diagrams.onprem.database", "Postgresql")],
    "onprem.mysql": [("diagrams.onprem.database", "MySQL"), ("diagrams.onprem.database", "Mysql")],
    "onprem.mariadb": [("diagrams.onprem.database", "MariaDB"), ("diagrams.onprem.database", "Mariadb")],
    "onprem.mongodb": [("diagrams.onprem.database", "MongoDB"), ("diagrams.onprem.database", "Mongodb")],
    "onprem.cassandra": [("diagrams.onprem.database", "Cassandra")],
    "onprem.mssql": [("diagrams.onprem.database", "MSSQL"), ("diagrams.onprem.database", "Mssql")],
    "onprem.oracle": [("diagrams.onprem.database", "Oracle")],
    "onprem.neo4j": [("diagrams.onprem.database", "Neo4J"), ("diagrams.onprem.database", "Neo4j")],
    "onprem.influxdb": [("diagrams.onprem.database", "Influxdb"), ("diagrams.onprem.database", "InfluxDB")],
    "onprem.clickhouse": [("diagrams.onprem.database", "Clickhouse"), ("diagrams.onprem.database", "ClickHouse")],
    "onprem.couchdb": [("diagrams.onprem.database", "CouchDB"), ("diagrams.onprem.database", "Couchdb")],
    "onprem.sql": [("diagrams.generic.database", "SQL"), ("diagrams.onprem.database", "PostgreSQL")],
    "onprem.redis": [("diagrams.onprem.inmemory", "Redis")],
    "onprem.memcached": [("diagrams.onprem.inmemory", "Memcached")],
    "onprem.hazelcast": [("diagrams.onprem.inmemory", "Hazelcast")],
    "onprem.kafka": [("diagrams.onprem.queue", "Kafka")],
    "onprem.rabbitmq": [("diagrams.onprem.queue", "RabbitMQ"), ("diagrams.onprem.queue", "Rabbitmq")],
    "onprem.activemq": [("diagrams.onprem.queue", "ActiveMQ"), ("diagrams.onprem.queue", "Activemq")],
    "onprem.nats": [("diagrams.onprem.queue", "Nats")],
    "onprem.zeromq": [("diagrams.onprem.queue", "ZeroMQ"), ("diagrams.onprem.queue", "Zeromq")],
    "onprem.celery": [("diagrams.onprem.queue", "Celery")],
    "onprem.zookeeper": [("diagrams.onprem.network", "Zookeeper"), ("diagrams.onprem.etcd", "Etcd"),
                         ("diagrams.generic.network", "Switch")],
    "onprem.nginx": [("diagrams.onprem.network", "Nginx")],
    "onprem.traefik": [("diagrams.onprem.network", "Traefik")],
    "onprem.haproxy": [("diagrams.onprem.network", "Haproxy"), ("diagrams.onprem.network", "HAProxy")],
    "onprem.envoy": [("diagrams.onprem.network", "Envoy")],
    "onprem.kong": [("diagrams.onprem.network", "Kong")],
    "onprem.istio": [("diagrams.onprem.network", "Istio")],
    "onprem.elasticsearch": [("diagrams.elastic.elasticsearch", "Elasticsearch"),
                             ("diagrams.onprem.search", "Solr")],
    "onprem.solr": [("diagrams.onprem.search", "Solr")],
    "onprem.minio": [("diagrams.onprem.storage", "Ceph"), ("diagrams.generic.storage", "Storage")],
    "onprem.vault": [("diagrams.onprem.security", "Vault")],
    "onprem.keycloak": [("diagrams.onprem.auth", "Oauth2Proxy"), ("diagrams.onprem.security", "Vault")],
    "onprem.prometheus": [("diagrams.onprem.monitoring", "Prometheus")],
    "onprem.grafana": [("diagrams.onprem.monitoring", "Grafana")],
    "onprem.sentry": [("diagrams.onprem.monitoring", "Sentry")],
    "onprem.newrelic": [("diagrams.onprem.monitoring", "Newrelic")],
    "onprem.loki": [("diagrams.onprem.logging", "Loki")],
    "onprem.fluentd": [("diagrams.onprem.logging", "Fluentd"), ("diagrams.onprem.logging", "Fluentbit")],
    "onprem.docker": [("diagrams.onprem.container", "Docker")],
    "onprem.helm": [("diagrams.onprem.iac", "Helm"), ("diagrams.k8s.ecosystem", "Helm")],
    "onprem.terraform": [("diagrams.onprem.iac", "Terraform")],
    "onprem.ansible": [("diagrams.onprem.iac", "Ansible")],
    "onprem.jenkins": [("diagrams.onprem.ci", "Jenkins")],
    "onprem.githubactions": [("diagrams.onprem.ci", "GithubActions")],
    "onprem.gitlabci": [("diagrams.onprem.ci", "Gitlabci"), ("diagrams.onprem.ci", "GitlabCI")],
    "onprem.circleci": [("diagrams.onprem.ci", "Circleci"), ("diagrams.onprem.ci", "CircleCI")],
    "onprem.airflow": [("diagrams.onprem.workflow", "Airflow")],
    "onprem.spark": [("diagrams.onprem.analytics", "Spark")],
    "onprem.dbt": [("diagrams.onprem.analytics", "Dbt"), ("diagrams.onprem.analytics", "Spark")],
    "onprem.beam": [("diagrams.onprem.analytics", "Beam"), ("diagrams.onprem.analytics", "Spark")],
    "onprem.mlflow": [("diagrams.onprem.mlops", "Mlflow"), ("diagrams.onprem.mlops", "Polyaxon")],

    # ===================== SaaS / third party =====================
    "saas.slack": [("diagrams.saas.chat", "Slack")],
    "saas.teams": [("diagrams.saas.chat", "Teams")],
    "saas.auth0": [("diagrams.saas.identity", "Auth0")],
    "saas.okta": [("diagrams.saas.identity", "Okta")],
    "saas.datadog": [("diagrams.saas.logging", "Datadog"), ("diagrams.onprem.monitoring", "Datadog")],
    "saas.snowflake": [("diagrams.saas.analytics", "Snowflake")],
    # No Stripe or SendGrid icon ships with `diagrams`. A neutral box labelled
    # "Stripe" is honest; borrowing another vendor's logo is actively wrong.
    "saas.stripe": [("diagrams.generic.blank", "Blank")],
    "saas.twilio": [("diagrams.saas.communication", "Twilio")],
    "saas.sendgrid": [("diagrams.generic.blank", "Blank")],
    "saas.cloudflare": [("diagrams.saas.cdn", "Cloudflare")],
    "saas.cloudinary": [("diagrams.saas.media", "Cloudinary")],
    "saas.algolia": [("diagrams.elastic.elasticsearch", "Elasticsearch"), ("diagrams.onprem.search", "Solr")],
    "saas.anthropic": [("diagrams.generic.blank", "Blank")],
    "saas.openai": [("diagrams.generic.blank", "Blank")],

    # ===================== Languages / frameworks =====================
    "programming.python": [("diagrams.programming.language", "Python")],
    "programming.nodejs": [("diagrams.programming.language", "Nodejs"), ("diagrams.programming.language", "Javascript")],
    "programming.typescript": [("diagrams.programming.language", "Typescript")],
    "programming.java": [("diagrams.programming.language", "Java")],
    "programming.go": [("diagrams.programming.language", "Go")],
    "programming.csharp": [("diagrams.programming.language", "Csharp")],
    "programming.ruby": [("diagrams.programming.language", "Ruby")],
    "programming.php": [("diagrams.programming.language", "Php")],
    "programming.rust": [("diagrams.programming.language", "Rust")],
    "programming.react": [("diagrams.programming.framework", "React")],
    "programming.vue": [("diagrams.programming.framework", "Vue")],
    "programming.angular": [("diagrams.programming.framework", "Angular")],
    "programming.svelte": [("diagrams.programming.framework", "Svelte")],
    "programming.django": [("diagrams.programming.framework", "Django")],
    "programming.flask": [("diagrams.programming.framework", "Flask")],
    "programming.fastapi": [("diagrams.programming.framework", "FastAPI"),
                            ("diagrams.programming.framework", "Fastapi"),
                            ("diagrams.programming.language", "Python")],
    "programming.spring": [("diagrams.programming.framework", "Spring")],
    "programming.rails": [("diagrams.programming.framework", "Rails")],
    "programming.laravel": [("diagrams.programming.framework", "Laravel")],
    "programming.graphql": [("diagrams.programming.framework", "Graphql"),
                            ("diagrams.programming.framework", "GraphQL")],

    # ===================== Generic fallbacks =====================
    "generic.user": [("diagrams.onprem.client", "Users"), ("diagrams.onprem.client", "User")],
    "generic.client": [("diagrams.onprem.client", "Client")],
    "generic.mobile": [("diagrams.generic.device", "Mobile")],
    "generic.browser": [("diagrams.onprem.client", "Client")],
    "generic.service": [("diagrams.generic.compute", "Rack"), ("diagrams.onprem.compute", "Server")],
    "generic.database": [("diagrams.generic.database", "SQL")],
    "generic.vectordb": [("diagrams.generic.database", "SQL")],
    "generic.storage": [("diagrams.generic.storage", "Storage")],
    "generic.firewall": [("diagrams.generic.network", "Firewall")],
    "generic.router": [("diagrams.generic.network", "Router")],
    "generic.switch": [("diagrams.generic.network", "Switch")],
    "generic.subnet": [("diagrams.generic.network", "Subnet")],
    "generic.http": [("diagrams.generic.network", "Router")],
    "generic.grpc": [("diagrams.generic.network", "Router")],
    "generic.jwt": [("diagrams.onprem.auth", "Oauth2Proxy"), ("diagrams.generic.blank", "Blank")],
    "generic.otel": [("diagrams.onprem.monitoring", "Prometheus")],
    "generic.ml": [("diagrams.generic.blank", "Blank")],
    "generic.llmframework": [("diagrams.generic.blank", "Blank")],
    "generic.dataframe": [("diagrams.generic.blank", "Blank")],
    "generic.bundler": [("diagrams.generic.blank", "Blank")],
    "generic.blank": [("diagrams.generic.blank", "Blank")],
}


# When a key is unknown entirely, pick something sensible for the role.
KIND_FALLBACK: dict[K, str] = {
    K.CLIENT: "generic.user",
    K.CDN: "generic.router",
    K.GATEWAY: "onprem.nginx",
    K.FRONTEND: "programming.react",
    K.SERVICE: "generic.service",
    K.FUNCTION: "generic.service",
    K.WORKER: "onprem.celery",
    K.QUEUE: "onprem.rabbitmq",
    K.STREAM: "onprem.kafka",
    K.DATABASE: "generic.database",
    K.CACHE: "onprem.redis",
    K.STORAGE: "generic.storage",
    K.SEARCH: "onprem.solr",
    K.ANALYTICS: "generic.service",
    K.ML: "generic.blank",
    K.AUTH: "generic.jwt",
    K.MONITORING: "onprem.prometheus",
    K.CICD: "onprem.docker",
    K.EXTERNAL: "generic.blank",
    K.INFRA: "generic.switch",
}


@functools.lru_cache(maxsize=512)
def _resolve_candidates(candidates: tuple[tuple[str, str], ...]) -> Any | None:
    """Import the first available (module, class) pair."""
    for module_path, class_name in candidates:
        try:
            module = importlib.import_module(module_path)
        except ImportError:
            continue
        node_class = getattr(module, class_name, None)
        if node_class is not None:
            return node_class
    return None


@functools.lru_cache(maxsize=64)
def _custom_node(asset: str) -> Any | None:
    """A factory that builds a `Custom` node for one of our own tiles.

    `resolve` promises a callable taking just a label, but `Custom` needs
    `(label, icon_path)` - hence the closure. Returns None if the asset is
    missing so the caller falls through to the normal icon chain.
    """
    path = ASSETS_DIR / f"{asset}.png"
    if not path.is_file():
        return None
    try:
        from diagrams.custom import Custom
    except ImportError:
        return None

    def make(label: str, _path: str = str(path)) -> Any:
        return Custom(label, _path)

    make.__name__ = f"Custom_{asset}"
    return make


def resolve(service: str, kind: K = K.SERVICE) -> Any:
    """Return a `diagrams` node class for a canonical service key.

    Falls back through: our own tile -> exact key -> provider-generic ->
    kind default -> Blank. Always returns something renderable.
    """
    # Our own tiles win: they exist precisely for keys where the best the
    # registry can do is an unlabelled blank box.
    asset = CUSTOM_ICONS.get(service)
    if asset:
        node = _custom_node(asset)
        if node is not None:
            return node

    candidates = ICON_REGISTRY.get(service)
    if candidates:
        node = _resolve_candidates(tuple(candidates))
        if node is not None:
            return node

    fallback_key = KIND_FALLBACK.get(kind, "generic.service")
    fallback = ICON_REGISTRY.get(fallback_key)
    if fallback:
        node = _resolve_candidates(tuple(fallback))
        if node is not None:
            return node

    # Last resort - Blank always exists in `diagrams`.
    node = _resolve_candidates((("diagrams.generic.blank", "Blank"),))
    if node is None:  # pragma: no cover - diagrams not installed
        raise ImportError("The `diagrams` package is not installed.")
    return node


def is_known(service: str) -> bool:
    return service in ICON_REGISTRY


def available() -> bool:
    """Whether `diagrams` (and therefore any icon) can be imported at all."""
    try:
        importlib.import_module("diagrams")
    except ImportError:
        return False
    return True
